import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
<<<<<<< HEAD
import Footer from "./components/Footer";
=======
>>>>>>> adde70d2afdcc294505f8e2467bcec8a3c016f62

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        {children}
<<<<<<< HEAD
        <Footer />
=======
>>>>>>> adde70d2afdcc294505f8e2467bcec8a3c016f62
      </body>
    </html>
  );
}
